const image = 'https://pics.craiyon.com/2023-08-02/7a951cac85bd4aa2b0e70dbaabb8404e.webp';
export const protocolList = [
  {
    id: '1',
    icon: image,
    title: 'Moonwell',
  },
  {
    id: '2',
    icon: image,
    title: 'Aerodrome',
  },
  {
    id: '3',
    icon: image,
    title: 'Morpho',
  },
];
export const strategyies: Array<any> = [
  {
    id: '1',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '2',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '3',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '4',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '5',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '6',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '7',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '8',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '9',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '10',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '11',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    id: '12',
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
];
