const image = 'https://pics.craiyon.com/2023-08-02/7a951cac85bd4aa2b0e70dbaabb8404e.webp';
export const strategyies: Array<any> = [
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Nurayyy.eth',
    tvl: '2.4m',
    estimate: '56.7%',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
];
