const image = 'https://pics.craiyon.com/2023-08-02/7a951cac85bd4aa2b0e70dbaabb8404e.webp';
export const feeds: Array<any> = [
  {
    photo: image,
    username: '@Nurayyy.eth',
    address: '0xc61...87f7a',
    date: '2h',
    percentage: '65.45',
    estimate: 'Est. APY',
    title: 'Moonwell - USDC',
    commentCount: 26,
    shareCount: 26,
    flashCount: 26,
    description: 'This strategy starts as an ease in for first and second quaterss of 2025',
    steps: [
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },

      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
  {
    photo: image,
    username: '@Gabby.eth',
    address: '0xc61...87f7a',
    date: '2h',
    percentage: '65.45',
    estimate: 'Est. APY',
    title: 'Moonwell - USDC',
    commentCount: 26,
    shareCount: 26,
    flashCount: 26,
    description: 'This strategy starts as an ease in for first and second quaterss of 2025',
    steps: [
      {
        variant: 'deposit',
        tokenA: 'Borrowed USDC',
        tokenB: 'Morpho',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'supply',
        tokenA: 'cbBTC',
        tokenB: 'moonWell',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        variant: 'borrow',
        tokenA: 'USDC',
        tokenB: 'Base',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
      {
        isLast: true,
        variant: 'stake',
        tokenA: 'DAI',
        tokenB: 'USDC',
        tokenAIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenAIcon_jgy241.png',
        tokenBIconURL: 'https://res.cloudinary.com/djzeufu4j/image/upload/v1732105634/tokenBIcon_wscb3p.png',
      },
    ],
  },
];
